name: oncue_mobile
description: OnCue mobile application
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^12.1.0
  flutter_secure_storage: ^11.1.1
  flutter_webrtc: ^1.6.2+hotfix.3
  kakao_flutter_sdk_common: ^2.0.1
  kakao_flutter_sdk_user: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Noto Sans KR
      fonts:
        - asset: assets/fonts/NotoSansKR-Variable.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Variable.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Variable.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR-Variable.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Variable.ttf
          weight: 800
